"""Make profile fields nullable

Revision ID: 3f5a8a3dd168
Revises: dc6ee9bccf9e
Create Date: 2025-04-30 20:34:12.847777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5a8a3dd168'
down_revision: Union[str, None] = 'dc6ee9bccf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employers', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completed')
    op.alter_column('employers', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
