"""add_match_score_to_applications

Revision ID: bd1ed39660ce
Revises: f7a0868b4ce8
Create Date: 2026-05-18 12:01:44.306772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1ed39660ce'
down_revision: Union[str, None] = 'f7a0868b4ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('match_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'match_score')
    # ### end Alembic commands ###
