"""create applications table properly

Revision ID: d0d81f1d8e11
Revises: 670d9c72c2e9
Create Date: 2026-05-15 11:23:49.867968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d81f1d8e11'
down_revision: Union[str, None] = '670d9c72c2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'reviewing', 'accepted', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job')
    )
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
