"""Initial tables

Revision ID: dc6ee9bccf9e
Revises: 5f4c8686eae5
Create Date: 2025-04-29 18:39:04.449953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6ee9bccf9e'
down_revision: Union[str, None] = '5f4c8686eae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_type', sa.Enum('candidate', 'employer', name='usertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.create_table('employers',
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('employer_id')
    )
    op.create_index(op.f('ix_employers_employer_id'), 'employers', ['employer_id'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_location', sa.String(length=100), nullable=False),
    sa.Column('skills_required', sa.JSON(), nullable=False),
    sa.Column('salary_range', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_status', sa.Enum('open', 'closed', 'paused', name='jobstatusenum'), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['employers.employer_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_employers_employer_id'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
